In [1]:
import sys
sys.path.append('/home/iceberg/notebooks/PyCon_LT_Workshop')

from helpers.utils import get_spark_session, get_yellow_taxi_data
spark = get_spark_session("getting_started")

from minio import Minio
client = Minio(
        "minio:9000",
        access_key="admin",
        secret_key="password",
        secure=False  # Set to True if your Minio server uses TLS/SSL
    )

def print_objects_in_warehouse(bucket_name):
    objects = client.list_objects(bucket_name, recursive=True)
    for obj in objects:
        print(obj.object_name, str(obj._size//1024) + "KB")
print_objects_in_warehouse("warehouse")

staging/yellow_taxi/data/00000-1-afaa0077-0731-4fd4-aed0-619421755d83-0-00001.parquet 37251KB
staging/yellow_taxi/data/00000-19-32e77607-82db-49c4-be96-67f47ec17724-0-00001.parquet 36874KB
staging/yellow_taxi/data/00000-2-4ec7c95b-1bcf-4247-838a-5168cca43043-0-00001.parquet 17295KB
staging/yellow_taxi/data/00000-2-4ec7c95b-1bcf-4247-838a-5168cca43043-0-00002.parquet 17373KB
staging/yellow_taxi/data/00000-2-4ec7c95b-1bcf-4247-838a-5168cca43043-0-00003.parquet 3525KB
staging/yellow_taxi/data/00000-5-3664f8f3-589d-44da-955f-cb1749f3a64a-0-00001.parquet 37251KB
staging/yellow_taxi/data/00001-2-afaa0077-0731-4fd4-aed0-619421755d83-0-00001.parquet 44630KB
staging/yellow_taxi/data/00001-20-32e77607-82db-49c4-be96-67f47ec17724-0-00001.parquet 44147KB
staging/yellow_taxi/data/00001-3-4ec7c95b-1bcf-4247-838a-5168cca43043-0-00001.parquet 17292KB
staging/yellow_taxi/data/00001-3-4ec7c95b-1bcf-4247-838a-5168cca43043-0-00002.parquet 17265KB
staging/yellow_taxi/data/00001-3-4ec7c95b-1bcf-4247-838a-5168cca43043-0-00003.parquet 10519KB
staging/yellow_taxi/data/00001-6-3664f8f3-589d-44da-955f-cb1749f3a64a-0-00001.parquet 44630KB
staging/yellow_taxi/metadata/00000-ae874524-b096-412f-8cb1-0c4760d6b2e9.metadata.json 3KB
staging/yellow_taxi/metadata/00001-eeaf7be4-5a21-4c31-92cb-58020f16f80e.metadata.json 4KB
staging/yellow_taxi/metadata/00002-0d55e1eb-df22-4269-a036-dde4cb852f3a.metadata.json 6KB
staging/yellow_taxi/metadata/00003-b1914d19-e499-4aee-b269-01e0ddb3ee06.metadata.json 7KB
staging/yellow_taxi/metadata/00004-1445a277-66ab-4dd5-a560-95ebb1a3ec50.metadata.json 8KB
staging/yellow_taxi/metadata/00005-4bdc158c-6655-456c-af82-8218a120897f.metadata.json 9KB
staging/yellow_taxi/metadata/00006-7cfafdbe-76f1-49c2-a3af-c2ad63d090ac.metadata.json 10KB
staging/yellow_taxi/metadata/85d522bf-4df1-48bb-bd49-bf17e4763200-m0.avro 8KB
staging/yellow_taxi/metadata/85d522bf-4df1-48bb-bd49-bf17e4763200-m1.avro 8KB
staging/yellow_taxi/metadata/873ac6bd-c08d-4a8b-810f-8a648bf2f782-m0.avro 8KB
staging/yellow_taxi/metadata/873ac6bd-c08d-4a8b-810f-8a648bf2f782-m1.avro 9KB
staging/yellow_taxi/metadata/ab4678a7-c205-4a14-ac42-eceebd074368-m0.avro 8KB
staging/yellow_taxi/metadata/db751d43-5f5e-4353-b847-bbd9bd57b54c-m0.avro 8KB
staging/yellow_taxi/metadata/optimized-m-b87a355b-b783-4b22-be22-d41d6d2c7d39.avro 9KB
staging/yellow_taxi/metadata/snap-3219656268123285048-1-8e97d062-6837-4197-a15d-29885e927f25.avro 4KB
staging/yellow_taxi/metadata/snap-4596078438615030908-1-ab4678a7-c205-4a14-ac42-eceebd074368.avro 4KB
staging/yellow_taxi/metadata/snap-5363513689733971433-1-db751d43-5f5e-4353-b847-bbd9bd57b54c.avro 4KB
staging/yellow_taxi/metadata/snap-7734203308380970130-1-873ac6bd-c08d-4a8b-810f-8a648bf2f782.avro 4KB
staging/yellow_taxi/metadata/snap-9160540137384676132-1-85d522bf-4df1-48bb-bd49-bf17e4763200.avro 4KB

24/03/29 16:20:18 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

In [2]:
%%sql
select * from staging.yellow_taxi

24/03/29 16:20:20 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

+----------+----------------------+-----------------------+-----------------+---------------+------------+--------------------+--------------+--------------+--------------+------+-------+---------+------------+--------------+-----------------------+--------------+----------------------+-------------+
| VendorID | tpep_pickup_datetime | tpep_dropoff_datetime | passenger_count | trip_distance | RatecodeID | store_and_fwd_flag | PULocationID | DOLocationID | payment_type | fare | extra | mta_tax | tip_amount | tolls_amount | improvement_surcharge | total_amount | congestion_surcharge | airport_fee |
+----------+----------------------+-----------------------+-----------------+---------------+------------+--------------------+--------------+--------------+--------------+------+-------+---------+------------+--------------+-----------------------+--------------+----------------------+-------------+
|        1 |  2022-01-01 00:35:40 |   2022-01-01 00:53:29 |             2.0 |           3.8 |        1.0 |                  N |          142 |          236 |            1 | 14.5 |   3.0 |     0.5 |       3.65 |          0.0 |                   0.3 |        21.95 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:33:43 |   2022-01-01 00:42:07 |             1.0 |           2.1 |        1.0 |                  N |          236 |           42 |            1 |  8.0 |   0.5 |     0.5 |        4.0 |          0.0 |                   0.3 |         13.3 |                  0.0 |         0.0 |
|        2 |  2022-01-01 00:53:21 |   2022-01-01 01:02:19 |             1.0 |          0.97 |        1.0 |                  N |          166 |          166 |            1 |  7.5 |   0.5 |     0.5 |       1.76 |          0.0 |                   0.3 |        10.56 |                  0.0 |         0.0 |
|        2 |  2022-01-01 00:25:21 |   2022-01-01 00:35:23 |             1.0 |          1.09 |        1.0 |                  N |          114 |           68 |            2 |  8.0 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |         11.8 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:36:48 |   2022-01-01 01:14:20 |             1.0 |           4.3 |        1.0 |                  N |           68 |          163 |            1 | 23.5 |   0.5 |     0.5 |        3.0 |          0.0 |                   0.3 |         30.3 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:40:15 |   2022-01-01 01:09:48 |             1.0 |          10.3 |        1.0 |                  N |          138 |          161 |            1 | 33.0 |   3.0 |     0.5 |       13.0 |         6.55 |                   0.3 |        56.35 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:20:50 |   2022-01-01 00:34:58 |             1.0 |          5.07 |        1.0 |                  N |          233 |           87 |            1 | 17.0 |   0.5 |     0.5 |        5.2 |          0.0 |                   0.3 |         26.0 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:13:04 |   2022-01-01 00:22:45 |             1.0 |          2.02 |        1.0 |                  N |          238 |          152 |            2 |  9.0 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |         12.8 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:30:02 |   2022-01-01 00:44:49 |             1.0 |          2.71 |        1.0 |                  N |          166 |          236 |            1 | 12.0 |   0.5 |     0.5 |       2.25 |          0.0 |                   0.3 |        18.05 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:48:52 |   2022-01-01 00:53:28 |             1.0 |          0.78 |        1.0 |                  N |          236 |          141 |            2 |  5.0 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |          8.8 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:55:03 |   2022-01-01 01:04:25 |             1.0 |          1.91 |        1.0 |                  N |          141 |          229 |            2 |  8.5 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |         12.3 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:31:06 |   2022-01-01 00:34:14 |             3.0 |          0.82 |        1.0 |                  N |          114 |           90 |            2 |  4.5 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |          8.3 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:41:07 |   2022-01-01 00:44:46 |             3.0 |          0.73 |        1.0 |                  N |          234 |          113 |            2 |  4.5 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |          8.3 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:56:34 |   2022-01-01 01:12:04 |             2.0 |          2.16 |        1.0 |                  N |          246 |           79 |            1 | 11.5 |   0.5 |     0.5 |       3.06 |          0.0 |                   0.3 |        18.36 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:39:46 |   2022-01-01 00:47:36 |             4.0 |          1.43 |        1.0 |                  N |           43 |          140 |            1 |  7.5 |   0.5 |     0.5 |       2.26 |          0.0 |                   0.3 |        13.56 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:58:06 |   2022-01-01 01:05:45 |             1.0 |          1.58 |        1.0 |                  N |          239 |          151 |            2 |  8.0 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |         11.8 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:33:52 |   2022-01-01 00:47:28 |             3.0 |           4.2 |        1.0 |                  N |          148 |          141 |            1 | 14.0 |   2.5 |     0.5 |       3.45 |          0.0 |                   0.3 |        20.75 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:53:54 |   2022-01-01 01:05:20 |             2.0 |           2.2 |        1.0 |                  N |          237 |          107 |            1 |  9.5 |   2.5 |     0.5 |       2.55 |          0.0 |                   0.3 |        15.35 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:00:44 |   2022-01-01 00:05:29 |             1.0 |           0.2 |        1.0 |                  N |            7 |            7 |            2 |  5.0 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |          6.3 |                  0.0 |         0.0 |
|        1 |  2022-01-01 00:35:50 |   2022-01-01 00:48:33 |             2.0 |           3.9 |        1.0 |                  N |          107 |          263 |            1 | 13.0 |   3.0 |     0.5 |       3.35 |          0.0 |                   0.3 |        20.15 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:49:14 |   2022-01-01 00:58:29 |             2.0 |           3.2 |        1.0 |                  N |          263 |          107 |            1 | 11.0 |   3.0 |     0.5 |       2.95 |          0.0 |                   0.3 |        17.75 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:06:10 |   2022-01-01 00:08:58 |             1.0 |           0.0 |        1.0 |                  N |          161 |          161 |            4 |  2.5 |   3.0 |     0.5 |        0.0 |          0.0 |                   0.3 |          6.3 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:09:01 |   2022-01-01 00:17:15 |             1.0 |           1.2 |        1.0 |                  N |          161 |           43 |            1 |  7.0 |   3.0 |     0.5 |       2.15 |          0.0 |                   0.3 |        12.95 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:30:06 |   2022-01-01 00:38:11 |             1.0 |           1.7 |        1.0 |                  N |          239 |           24 |            1 |  7.0 |   3.0 |     0.5 |       3.25 |          0.0 |                   0.3 |        14.05 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:46:41 |   2022-01-01 00:57:53 |             1.0 |           1.6 |        1.0 |                  N |          239 |          263 |            1 |  8.0 |   3.0 |     0.5 |       2.35 |          0.0 |                   0.3 |        14.15 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:14:00 |   2022-01-01 00:35:24 |             5.0 |          2.48 |        1.0 |                  N |          246 |          233 |            1 | 14.0 |   0.5 |     0.5 |       5.34 |          0.0 |                   0.3 |        23.14 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:46:09 |   2022-01-01 01:08:06 |             6.0 |          5.95 |        1.0 |                  N |           79 |          238 |            1 | 20.0 |   0.5 |     0.5 |       4.76 |          0.0 |                   0.3 |        28.56 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:52:53 |   2022-01-01 01:05:26 |             2.0 |           4.0 |        1.0 |                  N |          170 |          238 |            2 | 13.0 |   3.0 |     0.5 |        0.0 |          0.0 |                   0.3 |         16.8 |                  2.5 |         0.0 |
|        2 |  2022-01-01 18:04:06 |   2022-01-01 18:40:52 |             1.0 |           9.7 |        1.0 |                  N |          138 |           48 |            1 | 34.5 |   0.5 |     0.5 |       9.22 |         6.55 |                   0.3 |        55.32 |                  2.5 |        1.25 |
|        1 |  2022-01-01 00:23:54 |   2022-01-01 00:28:42 |             2.0 |           0.8 |        1.0 |                  N |          237 |          237 |            4 |  5.5 |   3.0 |     0.5 |        0.0 |          0.0 |                   0.3 |          9.3 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:59:06 |   2022-01-01 01:12:57 |             2.0 |           3.8 |        1.0 |                  Y |          233 |          238 |            2 | 13.5 |   3.0 |     0.5 |        0.0 |          0.0 |                   0.3 |         17.3 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:15:37 |   2022-01-01 00:31:13 |             2.0 |          3.07 |        1.0 |                  N |          162 |          249 |            1 | 13.0 |   0.5 |     0.5 |       3.36 |          0.0 |                   0.3 |        20.16 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:40:18 |   2022-01-01 01:02:50 |             3.0 |          2.79 |        1.0 |                  N |          114 |          186 |            1 | 15.5 |   0.5 |     0.5 |        2.9 |          0.0 |                   0.3 |         22.2 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:17:55 |   2022-01-01 00:27:45 |             1.0 |          4.22 |        1.0 |                  N |          138 |           92 |            2 | 14.0 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |        16.55 |                  0.0 |        1.25 |
|        2 |  2022-01-01 00:55:48 |   2022-01-01 01:14:24 |             1.0 |          6.67 |        1.0 |                  N |          138 |          229 |            1 | 21.0 |   0.5 |     0.5 |       15.0 |          0.0 |                   0.3 |        41.05 |                  2.5 |        1.25 |
|        2 |  2022-01-01 00:12:00 |   2022-01-01 00:22:47 |             1.0 |          5.18 |        1.0 |                  N |            4 |          262 |            1 | 16.0 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |         19.8 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:26:04 |   2022-01-01 00:44:54 |             1.0 |          5.03 |        1.0 |                  N |          262 |          249 |            1 | 18.5 |   0.5 |     0.5 |       6.69 |          0.0 |                   0.3 |        28.99 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:50:07 |   2022-01-01 00:55:44 |             1.0 |          1.05 |        1.0 |                  N |          249 |           90 |            1 |  6.0 |   0.5 |     0.5 |       1.96 |          0.0 |                   0.3 |        11.76 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:10:27 |   2022-01-01 00:41:59 |             1.0 |          17.1 |        2.0 |                  N |          132 |          170 |            1 | 52.0 |  3.75 |     0.5 |      15.75 |         6.55 |                   0.3 |        78.85 |                  2.5 |        1.25 |
|        1 |  2022-01-01 00:45:45 |   2022-01-01 01:01:45 |             1.0 |           4.8 |        1.0 |                  N |          170 |           74 |            2 | 16.5 |   3.0 |     0.5 |        0.0 |          0.0 |                   0.3 |         20.3 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:50:27 |   2022-01-01 00:59:28 |             1.0 |          2.66 |        1.0 |                  N |          132 |           10 |            2 | 10.0 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |        12.55 |                  0.0 |        1.25 |
|        2 |  2022-01-01 00:31:06 |   2022-01-01 00:58:26 |             3.0 |         19.14 |        2.0 |                  N |          132 |          263 |            1 | 52.0 |   0.0 |     0.5 |      12.37 |         6.55 |                   0.3 |        75.47 |                  2.5 |        1.25 |
|        2 |  2022-01-01 00:42:45 |   2022-01-01 00:56:15 |             2.0 |          6.49 |        1.0 |                  N |          138 |          112 |            1 | 19.5 |   0.5 |     0.5 |       6.62 |          0.0 |                   0.3 |        28.67 |                  0.0 |        1.25 |
|        2 |  2022-01-01 00:09:28 |   2022-01-01 00:14:42 |             5.0 |          1.43 |        1.0 |                  N |          137 |            4 |            2 |  6.5 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |         10.3 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:23:40 |   2022-01-01 00:30:14 |             5.0 |          1.27 |        1.0 |                  N |           79 |          249 |            1 |  7.0 |   0.5 |     0.5 |       2.16 |          0.0 |                   0.3 |        12.96 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:55:13 |   2022-01-01 01:04:56 |             4.0 |          2.07 |        1.0 |                  N |           90 |           45 |            2 |  9.0 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |         12.8 |                  2.5 |         0.0 |
|        2 |  2022-01-01 01:06:32 |   2022-01-01 01:29:25 |             4.0 |           4.9 |        1.0 |                  N |           45 |          141 |            1 | 18.0 |   0.5 |     0.5 |        2.0 |          0.0 |                   0.3 |         23.8 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:37:15 |   2022-01-01 00:52:51 |             2.0 |          7.87 |        1.0 |                  N |           70 |          236 |            1 | 23.5 |   0.5 |     0.5 |       5.08 |         6.55 |                   0.3 |        38.93 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:56:26 |   2022-01-01 01:25:09 |             1.0 |         18.81 |        2.0 |                  N |          132 |          148 |            1 | 52.0 |   0.0 |     0.5 |      11.31 |          0.0 |                   0.3 |        67.86 |                  2.5 |        1.25 |
|        1 |  2022-01-01 00:33:42 |   2022-01-01 01:01:49 |             1.0 |          19.5 |        1.0 |                  N |          132 |           47 |            1 | 52.0 |  1.75 |     0.5 |        0.0 |         6.55 |                   0.3 |         61.1 |                  0.0 |        1.25 |
|        1 |  2022-01-01 00:19:52 |   2022-01-01 00:26:57 |             2.0 |           0.4 |        1.0 |                  N |           48 |           48 |            2 |  6.0 |   3.0 |     0.5 |        0.0 |          0.0 |                   0.3 |          9.8 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:30:20 |   2022-01-01 00:52:10 |             1.0 |           2.7 |        1.0 |                  N |           48 |           79 |            1 | 15.0 |   3.0 |     0.5 |       3.75 |          0.0 |                   0.3 |        22.55 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:58:11 |   2022-01-01 01:10:02 |             4.0 |           4.4 |        1.0 |                  N |          107 |           87 |            1 | 14.5 |   3.0 |     0.5 |       3.65 |          0.0 |                   0.3 |        21.95 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:50:22 |   2022-01-01 01:07:20 |             1.0 |           4.3 |        1.0 |                  Y |           90 |          262 |            1 | 15.0 |   3.0 |     0.5 |       3.75 |          0.0 |                   0.3 |        22.55 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:21:01 |   2022-01-01 00:25:53 |             2.0 |           1.9 |        1.0 |                  N |          137 |          140 |            1 |  7.0 |   3.0 |     0.5 |        1.0 |          0.0 |                   0.3 |         11.8 |                  2.5 |         0.0 |
|        1 |  2022-01-01 00:43:49 |   2022-01-01 01:03:06 |             3.0 |           2.3 |        1.0 |                  N |          161 |           79 |            3 | 13.5 |   3.0 |     0.5 |        0.0 |          0.0 |                   0.3 |         17.3 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:33:50 |   2022-01-01 00:52:14 |             1.0 |          4.62 |        1.0 |                  N |           68 |          238 |            1 | 17.0 |   0.5 |     0.5 |       4.16 |          0.0 |                   0.3 |        24.96 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:15:42 |   2022-01-01 00:20:33 |             2.0 |          1.33 |        1.0 |                  N |          263 |          140 |            1 |  6.0 |   0.5 |     0.5 |       1.96 |          0.0 |                   0.3 |        11.76 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:40:57 |   2022-01-01 01:12:08 |             1.0 |           2.7 |        1.0 |                  N |          161 |          142 |            1 | 19.5 |   0.5 |     0.5 |       6.99 |          0.0 |                   0.3 |        30.29 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:46:19 |   2022-01-01 01:15:22 |             2.0 |          3.81 |        1.0 |                  N |          162 |          238 |            1 | 19.5 |   0.5 |     0.5 |       4.66 |          0.0 |                   0.3 |        27.96 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:24:13 |   2022-01-01 00:38:50 |             1.0 |          2.73 |        1.0 |                  N |          211 |          170 |            2 | 12.0 |   0.5 |     0.5 |        0.0 |          0.0 |                   0.3 |         15.8 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:51:40 |   2022-01-01 00:57:29 |             1.0 |          0.61 |        1.0 |                  N |          113 |           79 |            1 |  5.5 |   0.5 |     0.5 |        2.0 |          0.0 |                   0.3 |         11.3 |                  2.5 |         0.0 |
|        2 |  2022-01-01 00:29:45 |   2022-01-01 00:42:02 |             4.0 |          1.74 |        1.0 |                  N |          164 |          137 |            1 |  9.5 |   0.5 |     0.5 |       2.66 |          0.0 |                   0.3 |        15.96 |                  2.5 |         0.0 |

In [3]:
%%sql
create table if not exists staging.aggregated_taxi_per_vendor_date as
select 
date(tpep_pickup_datetime) as dt,
vendorID as vendor_id,
count(1)
from staging.yellow_taxi
group by 1,2

++
||
++
++

In [4]:
%%sql 
select * from staging.aggregated_taxi_per_vendor_date

+------------+-----------+----------+
|         dt | vendor_id | count(1) |
+------------+-----------+----------+
| 2022-01-06 |         1 |    24388 |
| 2022-01-03 |         1 |    22530 |
| 2022-01-14 |         2 |    65174 |
| 2022-02-22 |         2 |    70604 |
| 2022-01-12 |         1 |    24580 |
| 2022-01-01 |         2 |    45711 |
| 2022-01-25 |         2 |    59934 |
| 2022-05-18 |         2 |        2 |
| 2022-01-13 |         2 |    58930 |
| 2022-01-03 |         2 |    49706 |
| 2009-01-01 |         2 |       12 |
| 2022-01-14 |         1 |    28349 |
| 2022-01-12 |         2 |    55460 |
| 2022-01-02 |         1 |    16799 |
| 2022-02-01 |         2 |    63322 |
| 2022-01-15 |         1 |    25650 |
| 2022-01-09 |         1 |    18828 |
| 2022-04-06 |         2 |        1 |
| 2008-12-31 |         2 |        8 |
| 2022-01-08 |         2 |    59012 |
| 2022-01-10 |         1 |    23056 |
| 2022-01-07 |         1 |    21162 |
| 2022-01-13 |         1 |    25746 |
| 2022-01-02 |         2 |    41563 |
| 2022-01-01 |         1 |    17671 |
| 2022-01-15 |         2 |    62982 |
| 2021-12-31 |         2 |       24 |
| 2022-01-11 |         1 |    24417 |
| 2022-03-09 |         2 |        1 |
| 2022-01-16 |         1 |    20908 |
| 2022-01-16 |         2 |    51790 |
| 2022-01-11 |         2 |    52994 |
| 2022-01-06 |         2 |    55354 |
| 2022-01-07 |         2 |    50257 |
| 2022-01-09 |         2 |    45141 |
| 2022-01-04 |         1 |    23085 |
| 2022-03-15 |         2 |        3 |
| 2022-01-10 |         2 |    50439 |
| 2022-01-05 |         1 |    22894 |
| 2022-01-05 |         2 |    51455 |
| 2022-01-08 |         1 |    24104 |
| 2022-01-04 |         2 |    51310 |
| 2022-01-27 |         2 |    68648 |
| 2022-01-19 |         2 |    60001 |
| 2022-01-26 |         1 |    29906 |
| 2022-01-23 |         2 |    53871 |
| 2022-01-24 |         2 |    53371 |
| 2022-01-27 |         1 |    30848 |
| 2022-01-19 |         1 |    26368 |
| 2022-01-20 |         2 |    62777 |
| 2022-01-30 |         2 |    51788 |
| 2022-01-20 |         1 |    27761 |
| 2022-01-28 |         1 |    28951 |
| 2022-01-22 |         2 |    68262 |
| 2022-01-29 |         2 |    25084 |
| 2022-01-30 |         1 |    19348 |
| 2022-01-24 |         1 |    24929 |
| 2022-01-22 |         1 |    28246 |
| 2022-01-28 |         2 |    66651 |
| 2022-01-29 |         1 |     9268 |
| 2022-01-21 |         2 |    69912 |
| 2022-01-17 |         1 |    18712 |
| 2022-01-17 |         2 |    44736 |
| 2022-01-18 |         1 |    26477 |
| 2022-01-25 |         1 |    27151 |
| 2022-01-23 |         1 |    22959 |
| 2022-01-26 |         2 |    66567 |
| 2022-01-21 |         1 |    30866 |
| 2022-01-18 |         2 |    57878 |
| 2022-02-09 |         1 |    32246 |
| 2022-02-12 |         1 |    35147 |
| 2022-02-13 |         2 |    66731 |
| 2022-02-03 |         1 |    31559 |
| 2022-02-10 |         1 |    34093 |
| 2022-02-09 |         2 |    73459 |
| 2022-02-02 |         2 |    64422 |
| 2022-03-01 |         2 |       12 |
| 2022-04-12 |         2 |        3 |
| 2022-02-14 |         2 |    76168 |
| 2022-05-24 |         2 |        1 |
| 2022-03-22 |         2 |        2 |
| 2003-01-05 |         2 |        1 |
| 2022-02-08 |         2 |    70839 |
| 2022-05-03 |         2 |        3 |
| 2022-02-01 |         1 |    28727 |
| 2022-02-02 |         1 |    27854 |
| 2022-02-06 |         1 |    25877 |
| 2022-02-11 |         2 |    81674 |
| 2022-02-03 |         2 |    72603 |
| 2022-02-07 |         2 |    60934 |
| 2022-02-04 |         1 |    33003 |
| 2022-02-08 |         1 |    31619 |
| 2022-02-11 |         1 |    35736 |
| 2022-02-10 |         2 |    78369 |
| 2022-02-06 |         2 |    62172 |
| 2022-01-31 |         2 |    59270 |
| 2022-02-04 |         2 |    77042 |
| 2022-02-12 |         2 |    84388 |
| 2022-02-28 |         2 |    70305 |
| 2022-02-07 |         1 |    27625 |
+------------+-----------+----------+

In [5]:
%%sql
ALTER TABLE staging.aggregated_taxi_per_vendor_date
SET TBLPROPERTIES (
    'write.wap.enabled'='true'
)

++
||
++
++

In [6]:
%%sql
ALTER TABLE staging.aggregated_taxi_per_vendor_date
CREATE BRANCH manual_hot_fix

++
||
++
++

In [14]:
spark.conf.set('spark.wap.branch', 'manual_hot_fix')

In [8]:
%%sql
delete from staging.aggregated_taxi_per_vendor_date
where vendor_id = 6

++
||
++
++

In [9]:
%%sql

SELECT vendor_id
FROM  staging.aggregated_taxi_per_vendor_date.branch_manual_hot_fix
GROUP BY vendor_id

+-----------+
| vendor_id |
+-----------+
|         5 |
|         1 |
|         2 |
+-----------+

In [10]:
%%sql

SELECT vendor_id
FROM  staging.aggregated_taxi_per_vendor_date.branch_main
GROUP BY vendor_id

+-----------+
| vendor_id |
+-----------+
|         6 |
|         5 |
|         1 |
|         2 |
+-----------+

In [11]:
print_objects_in_warehouse("warehouse")

staging/aggregated_taxi_per_vendor_date/data/00000-11-146c816e-61d7-46da-a5d1-03a145d3fa47-0-00001.parquet 2KB
staging/aggregated_taxi_per_vendor_date/data/00000-6-b17d2ddd-2a29-4028-a76f-7e2c7da36fc5-0-00001.parquet 2KB
staging/aggregated_taxi_per_vendor_date/metadata/00000-b129cac9-ca9f-4f77-ba35-210754c0eddb.metadata.json 2KB
staging/aggregated_taxi_per_vendor_date/metadata/00001-4b6805a8-9ab9-4874-b2df-81a97e5fd3f5.metadata.json 2KB
staging/aggregated_taxi_per_vendor_date/metadata/00002-f3247c59-464a-4456-bd4b-61c7238ee394.metadata.json 2KB
staging/aggregated_taxi_per_vendor_date/metadata/00003-e7c6e6ea-92ed-4f00-952d-d35af8047289.metadata.json 3KB
staging/aggregated_taxi_per_vendor_date/metadata/1a4bcaf0-6855-4316-9a69-42b4963917ef-m0.avro 6KB
staging/aggregated_taxi_per_vendor_date/metadata/1a4bcaf0-6855-4316-9a69-42b4963917ef-m1.avro 6KB
staging/aggregated_taxi_per_vendor_date/metadata/c799410c-53a8-4f54-b21d-064c838960bd-m0.avro 6KB
staging/aggregated_taxi_per_vendor_date/metadata/snap-1079450372298633771-1-1a4bcaf0-6855-4316-9a69-42b4963917ef.avro 4KB
staging/aggregated_taxi_per_vendor_date/metadata/snap-4722644808567071556-1-c799410c-53a8-4f54-b21d-064c838960bd.avro 4KB
staging/yellow_taxi/data/00000-1-afaa0077-0731-4fd4-aed0-619421755d83-0-00001.parquet 37251KB
staging/yellow_taxi/data/00000-19-32e77607-82db-49c4-be96-67f47ec17724-0-00001.parquet 36874KB
staging/yellow_taxi/data/00000-2-4ec7c95b-1bcf-4247-838a-5168cca43043-0-00001.parquet 17295KB
staging/yellow_taxi/data/00000-2-4ec7c95b-1bcf-4247-838a-5168cca43043-0-00002.parquet 17373KB
staging/yellow_taxi/data/00000-2-4ec7c95b-1bcf-4247-838a-5168cca43043-0-00003.parquet 3525KB
staging/yellow_taxi/data/00000-5-3664f8f3-589d-44da-955f-cb1749f3a64a-0-00001.parquet 37251KB
staging/yellow_taxi/data/00001-2-afaa0077-0731-4fd4-aed0-619421755d83-0-00001.parquet 44630KB
staging/yellow_taxi/data/00001-20-32e77607-82db-49c4-be96-67f47ec17724-0-00001.parquet 44147KB
staging/yellow_taxi/data/00001-3-4ec7c95b-1bcf-4247-838a-5168cca43043-0-00001.parquet 17292KB
staging/yellow_taxi/data/00001-3-4ec7c95b-1bcf-4247-838a-5168cca43043-0-00002.parquet 17265KB
staging/yellow_taxi/data/00001-3-4ec7c95b-1bcf-4247-838a-5168cca43043-0-00003.parquet 10519KB
staging/yellow_taxi/data/00001-6-3664f8f3-589d-44da-955f-cb1749f3a64a-0-00001.parquet 44630KB
staging/yellow_taxi/metadata/00000-ae874524-b096-412f-8cb1-0c4760d6b2e9.metadata.json 3KB
staging/yellow_taxi/metadata/00001-eeaf7be4-5a21-4c31-92cb-58020f16f80e.metadata.json 4KB
staging/yellow_taxi/metadata/00002-0d55e1eb-df22-4269-a036-dde4cb852f3a.metadata.json 6KB
staging/yellow_taxi/metadata/00003-b1914d19-e499-4aee-b269-01e0ddb3ee06.metadata.json 7KB
staging/yellow_taxi/metadata/00004-1445a277-66ab-4dd5-a560-95ebb1a3ec50.metadata.json 8KB
staging/yellow_taxi/metadata/00005-4bdc158c-6655-456c-af82-8218a120897f.metadata.json 9KB
staging/yellow_taxi/metadata/00006-7cfafdbe-76f1-49c2-a3af-c2ad63d090ac.metadata.json 10KB
staging/yellow_taxi/metadata/85d522bf-4df1-48bb-bd49-bf17e4763200-m0.avro 8KB
staging/yellow_taxi/metadata/85d522bf-4df1-48bb-bd49-bf17e4763200-m1.avro 8KB
staging/yellow_taxi/metadata/873ac6bd-c08d-4a8b-810f-8a648bf2f782-m0.avro 8KB
staging/yellow_taxi/metadata/873ac6bd-c08d-4a8b-810f-8a648bf2f782-m1.avro 9KB
staging/yellow_taxi/metadata/ab4678a7-c205-4a14-ac42-eceebd074368-m0.avro 8KB
staging/yellow_taxi/metadata/db751d43-5f5e-4353-b847-bbd9bd57b54c-m0.avro 8KB
staging/yellow_taxi/metadata/optimized-m-b87a355b-b783-4b22-be22-d41d6d2c7d39.avro 9KB
staging/yellow_taxi/metadata/snap-3219656268123285048-1-8e97d062-6837-4197-a15d-29885e927f25.avro 4KB
staging/yellow_taxi/metadata/snap-4596078438615030908-1-ab4678a7-c205-4a14-ac42-eceebd074368.avro 4KB
staging/yellow_taxi/metadata/snap-5363513689733971433-1-db751d43-5f5e-4353-b847-bbd9bd57b54c.avro 4KB
staging/yellow_taxi/metadata/snap-7734203308380970130-1-873ac6bd-c08d-4a8b-810f-8a648bf2f782.avro 4KB
staging/yellow_taxi/metadata/snap-9160540137384676132-1-85d522bf-4df1-48bb-bd49-bf17e4763200.avro 4KB

In [12]:
spark.conf.unset('spark.wap.branch')

In [15]:
%%sql
SELECT vendor_id
FROM  staging.aggregated_taxi_per_vendor_date.branch_main
GROUP BY vendor_id

+-----------+
| vendor_id |
+-----------+
|         6 |
|         5 |
|         1 |
|         2 |
+-----------+

## How to publish my changes to main then?

In [16]:
%%sql
SELECT * FROM staging.aggregated_taxi_per_vendor_date.refs

+----------------+--------+---------------------+-------------------------+-----------------------+------------------------+
|           name |   type |         snapshot_id | max_reference_age_in_ms | min_snapshots_to_keep | max_snapshot_age_in_ms |
+----------------+--------+---------------------+-------------------------+-----------------------+------------------------+
| manual_hot_fix | BRANCH | 1079450372298633771 |                    None |                  None |                   None |
|           main | BRANCH | 4722644808567071556 |                    None |                  None |                   None |
+----------------+--------+---------------------+-------------------------+-----------------------+------------------------+

In [21]:
%%sql
select * from staging.aggregated_taxi_per_vendor_date.snapshots

+----------------------------+---------------------+---------------------+-----------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|               committed_at |         snapshot_id |           parent_id | operation |                                                                                                                        manifest_list |                                                                                                                                                                                                                                                                                                                                                                                                       summary |
+----------------------------+---------------------+---------------------+-----------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2024-03-29 16:20:27.205000 | 4722644808567071556 |                None |    append | s3://warehouse/staging/aggregated_taxi_per_vendor_date/metadata/snap-4722644808567071556-1-c799410c-53a8-4f54-b21d-064c838960bd.avro |                                                                                    {'spark.app.id': 'local-1711729217511', 'changed-partition-count': '1', 'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '236', 'total-position-deletes': '0', 'added-files-size': '2330', 'total-delete-files': '0', 'total-files-size': '2330', 'total-records': '236', 'total-data-files': '1'} |
| 2024-03-29 16:20:41.820000 | 1079450372298633771 | 4722644808567071556 | overwrite | s3://warehouse/staging/aggregated_taxi_per_vendor_date/metadata/snap-1079450372298633771-1-1a4bcaf0-6855-4316-9a69-42b4963917ef.avro | {'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '177', 'deleted-data-files': '1', 'deleted-records': '236', 'total-records': '177', 'spark.app.id': 'local-1711729217511', 'removed-files-size': '2330', 'changed-partition-count': '1', 'total-position-deletes': '0', 'added-files-size': '2077', 'total-delete-files': '0', 'total-files-size': '2077', 'total-data-files': '1'} |
+----------------------------+---------------------+---------------------+-----------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

In [18]:
query = f"""
SELECT snapshot_id
FROM staging.aggregated_taxi_per_vendor_date.refs
WHERE name = 'manual_hot_fix'
"""
wap_snapshot_id = spark.sql(query).head().snapshot_id

In [19]:
wap_snapshot_id

1079450372298633771

In [20]:
publish_query = f"CALL system.cherrypick_snapshot('staging.aggregated_taxi_per_vendor_date', {wap_snapshot_id})"

%sql $publish_query

+---------------------+---------------------+
|  source_snapshot_id | current_snapshot_id |
+---------------------+---------------------+
| 1079450372298633771 | 1079450372298633771 |
+---------------------+---------------------+

In [27]:
%%sql
CALL system.fast_forward('staging.aggregated_taxi_per_vendor_date', 'main', 'manual_hot_fix')

+----------------+---------------------+---------------------+
| branch_updated |        previous_ref |         updated_ref |
+----------------+---------------------+---------------------+
|           main | 1079450372298633771 | 1079450372298633771 |
+----------------+---------------------+---------------------+

In [28]:
%%sql
select * from staging.aggregated_taxi_per_vendor_date.snapshots

+----------------------------+---------------------+---------------------+-----------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|               committed_at |         snapshot_id |           parent_id | operation |                                                                                                                        manifest_list |                                                                                                                                                                                                                                                                                                                                                                                                       summary |
+----------------------------+---------------------+---------------------+-----------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2024-03-29 16:20:27.205000 | 4722644808567071556 |                None |    append | s3://warehouse/staging/aggregated_taxi_per_vendor_date/metadata/snap-4722644808567071556-1-c799410c-53a8-4f54-b21d-064c838960bd.avro |                                                                                    {'spark.app.id': 'local-1711729217511', 'changed-partition-count': '1', 'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '236', 'total-position-deletes': '0', 'added-files-size': '2330', 'total-delete-files': '0', 'total-files-size': '2330', 'total-records': '236', 'total-data-files': '1'} |
| 2024-03-29 16:20:41.820000 | 1079450372298633771 | 4722644808567071556 | overwrite | s3://warehouse/staging/aggregated_taxi_per_vendor_date/metadata/snap-1079450372298633771-1-1a4bcaf0-6855-4316-9a69-42b4963917ef.avro | {'added-data-files': '1', 'total-equality-deletes': '0', 'added-records': '177', 'deleted-data-files': '1', 'deleted-records': '236', 'total-records': '177', 'spark.app.id': 'local-1711729217511', 'removed-files-size': '2330', 'changed-partition-count': '1', 'total-position-deletes': '0', 'added-files-size': '2077', 'total-delete-files': '0', 'total-files-size': '2077', 'total-data-files': '1'} |
+----------------------------+---------------------+---------------------+-----------+--------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+